### ISSUE TITLE
Stuck on 9.6

### ISSUE THREAD

**Issue by Beosnook** [smfoote/kittenbook#3]
Hello, I don't know if this is the right place to ask for help about your book, so sorry if I'm in the wrong place. I'm currently going through your book, and I am completely stumped with adding in this .jshintrc file in Chapter 9.

I have everything written in Gruntfile.js and .jshintrc exactly as you have it in both the book and on this website, and yet when I try to run grunt in the command prompt, it says it can't parse the config file: .jshintrc

Which I guess means it simply can't interpret what is written in the file? I have no clue what I could be doing wrong as I have it written exactly as it appears on this website, and my searching on the internet trying to figure it out is not yielding any results. Any help would be greatly appreciated.

**Comment by smfoote** [comment]
This is a great place to ask questions. My first thought is that maybe you added the ellipsis (`...`) as they are shown in the code example. If that's the case, they should be removed - you'll find ellipsis in code examples to show that there is more code that is not shown. The full code for 9.6 can be found in this repo on the [9.6 branch](https://github.com/smfoote/kittenbook/tree/9.6). I hope that helps!

If that doesn't solve the problem, please post your `.jshintrc` and `Grunfile.js` in here, and I'll take a look.

**Comment by Beosnook** [comment]
Thank you so much for the response. I didn't add the ellipsis, so we can rule that out.

Here is my `.jshintrc `

```
{
  "predef": {
    "kittenbook": true,
    "kbValues": true,
    "prompt": true
  },

  "bitwise": true
  "camelcase": true
  "curly": true,
  "eqeqeq": true,
  "immed": true,
  "indent": 2,
  "latedef": true,
  "quotmark": "single",
  "undef": true,
  "unused": true,
  "strict": false,
  "trailing": true,

  "browser": true
}
 
```
and here is the `Gruntfile.js`
```

module.exports = function(grunt){
	// Project configuration
	grunt.initConfig({
		concat: {
			release: {
				src: ['js/values.js', 'js/prompt.js', 'js/getImages.js', 'js/replaceImages.js', 'js/main.js'],
				dest: 'release/main.js'
			}
		},
		copy: {
			release: {
				src: 'manifest.json',
				dest: 'release/manifest.json'
			}
		},
		jshint: {
			options: {
				jshintrc: '.jshintrc'
			},
			files: ['release/main.js']
		},
		watch: {
			files: ['<%=jshint.files %>', 'manifest.json'],
			tasks: ['default']
		}
	});

	// Load Grunt plugins
	grunt.loadNpmTasks('grunt-contrib-concat');
	grunt.loadNpmTasks('grunt-contrib-copy');
	grunt.loadNpmTasks('grunt-contrib-jshint');
	grunt.loadNpmTasks('grunt-contrib-watch');

	// Register tasks
	grunt.registerTask('default', ['concat', 'jshint', 'copy']);
};
```

**Comment by smfoote** [comment]
Looks like you are missing some commas in your .jshintrc:

```
  "bitwise": true
  "camelcase": true
```

should be 

```
  "bitwise": true,
  "camelcase": true,
```

**Comment by Beosnook** [comment]
Wow, I feel dumb haha. Well at least now I can move on to fixing the errors that were actually supposed to pop up. Thank you so much for your time and your help, I'm glad it was just a simple typo.

**Comment by smfoote** [comment]
👍
